In [7]:
from lexnlp.extract.rcare.readutils import DataFrameUtils as Utils
import spacy;
s_nlp = spacy.load('en_core_web_lg');
from spacy import displacy
import logging

logging.basicConfig(filename='spacy_sections.log',format='%(module)s||%(funcName)s||[%(process)d:%(thread)d||%(asctime)s||%(levelname)s||%(message)s', level=logging.DEBUG,
                    datefmt=logging.Formatter.default_time_format)

import pandas as pd
import numpy as np
from multiprocessing import Pool
print (Utils.DATA_PATH)
print (Utils.DATA_DIRS)

data/lexpredict-contraxsuite-samples/agreements/
['.ipynb_checkpoints', '001.csv', 'construction', 'credit', 'employment', 'eta_citi_2017.txt', 'joyee-ppapadim.pdf', 'joyee-ppapadim.txt', 'severance', 'software_license']

In [11]:
from spacy.matcher import PhraseMatcher

In [12]:
file_text = Utils.read_file_data(Utils.DATA_PATH + 'eta_citi_2017.txt')

In [13]:
matcher = PhraseMatcher(s_nlp.vocab)
matcher.add('ADDENDUM', None, s_nlp(u"ADDENDUM"))
matcher.add('DMA', None, s_nlp(u"DIRECT MARKET ACCESS"))
doc = s_nlp(file_text)
matches = matcher(doc)

In [6]:
matches

[(7358696156156570218, 6403, 6404),
 (7358696156156570218, 7445, 7446),
 (3364423310468807655, 7447, 7450),
 (7358696156156570218, 7619, 7620),
 (3364423310468807655, 7621, 7624),
 (7358696156156570218, 11128, 11129),
 (3364423310468807655, 11130, 11133),
 (7358696156156570218, 11400, 11401),
 (3364423310468807655, 11978, 11981),
 (7358696156156570218, 12564, 12565)]

In [19]:
prev_end = 0
spans = [];
for id, pos_s, pos_e in matches:
    if(prev_end == 0):
        spans.append(doc[prev_end: pos_s])
    else:        
        spans.append(doc[prev_end: pos_s])
        print(prev_end, pos_s, pos_e)
    prev_end = pos_s    
spans.append(doc[prev_end: ])

6403 7445 7446
7445 7447 7450
7447 7619 7620
7619 7621 7624
7621 11128 11129
11128 11130 11133
11130 11400 11401
11400 11978 11981
11978 12564 12565

In [ ]:
span = spans[10]
span

In [54]:
len_i = len(spans)
len_j = len(spans)
similarity = [.0] * len_i
for i in range(len_i):
    span_i = spans[i]
    similarity[i] = [.0] * len_j
    for j in range(len_j):
        span_j = spans[j]
        similarity[i][j] = span_i.similarity(span_j)
#similarity

[[1.0,
  0.9885579135468592,
  0.38196259671262794,
  0.9485644566372248,
  0.5129316250061882,
  0.9875285090734407,
  0.5013495519240577,
  0.84531203414007,
  0.9788825319127181,
  0.9713887633967195,
  0.5652312368551968],
 [0.9885579135468592,
  1.0,
  0.3750803020216506,
  0.9501820446201122,
  0.5163748194803723,
  0.97945437277901,
  0.5045632421452747,
  0.8460276375565547,
  0.9802317202476762,
  0.9683561070454266,
  0.5545097730269505],
 [0.38196259671262794,
  0.3750803020216506,
  1.0,
  0.36238442372006696,
  1.0,
  0.4005159545069138,
  1.0,
  0.38130773723086814,
  0.38855778795153884,
  0.35126852234184563,
  0.27638171944783707],
 [0.9485644566372248,
  0.9501820446201122,
  0.36238442372006696,
  1.0,
  0.4739724715339007,
  0.9515187569275027,
  0.4609776165553904,
  0.9114618045925136,
  0.9656780298431796,
  0.9554028039208551,
  0.5529488115652115],
 [0.5129316250061882,
  0.5163748194803723,
  1.0,
  0.4739724715339007,
  1.0,
  0.5256082126974415,
  1.0,
  0.4546280661316902,
  0.5228941236533741,
  0.4907471201140555,
  0.30866070869091866],
 [0.9875285090734407,
  0.97945437277901,
  0.4005159545069138,
  0.9515187569275027,
  0.5256082126974415,
  1.0,
  0.5139845774493631,
  0.8815515574123433,
  0.9722717018873804,
  0.9744544149845819,
  0.5939705639855167],
 [0.5013495519240577,
  0.5045632421452747,
  1.0,
  0.4609776165553904,
  1.0,
  0.5139845774493631,
  1.0,
  0.444327455407279,
  0.5134097917150644,
  0.4702843437932423,
  0.30796613341815104],
 [0.84531203414007,
  0.8460276375565547,
  0.38130773723086814,
  0.9114618045925136,
  0.4546280661316902,
  0.8815515574123433,
  0.444327455407279,
  1.0,
  0.8579930766539267,
  0.8828899507970233,
  0.6108791552225233],
 [0.9788825319127181,
  0.9802317202476762,
  0.38855778795153884,
  0.9656780298431796,
  0.5228941236533741,
  0.9722717018873804,
  0.5134097917150644,
  0.8579930766539267,
  1.0,
  0.9707384745053873,
  0.5710916916847371],
 [0.9713887633967195,
  0.9683561070454266,
  0.35126852234184563,
  0.9554028039208551,
  0.4907471201140555,
  0.9744544149845819,
  0.4702843437932423,
  0.8828899507970233,
  0.9707384745053873,
  1.0,
  0.5652905424900408],
 [0.5652312368551968,
  0.5545097730269505,
  0.27638171944783707,
  0.5529488115652115,
  0.30866070869091866,
  0.5939705639855167,
  0.30796613341815104,
  0.6108791552225233,
  0.5710916916847371,
  0.5652905424900408,
  1.0]]

In [14]:
def spacy_docs (docs):
    s_docs = [];
    for doc in docs:
        s_docs.append(s_nlp(doc))
    
    return s_docs

def display_ents(spacy_doc, filter_labels = ['ORG','CARDINAL', 'PERSON', 'ORDINAL', 'PRODUCT'], nrows = 50 ):
    i = 0;
    for ent in spacy_doc.ents:
        if(ent.label_ in filter_labels):
            print (ent.text, ent.label_, ent.start_char, ent.end_char, 'XX' + doc[ent.start_char: ent.end_char].text)
            i = i + 1;
            if(i> nrows): break;

In [53]:
#display_ents(doc, filter_labels = ['CARDINAL', 'ORDINAL'])
from scipy import spatial
1 - spatial.distance.cosine(spans[0].vector, spans[1].vector)
#np.cosin(spans[0].vector_norm, spans[1].vector_norm) , spans[2].vector_norm

0.9885579347610474

In [1]:
import spacy
from spacy.matcher import PhraseMatcher, Matcher
from spacy.tokens import Span, Doc, Token
import random

def tokens (doc):
    tokens = []
    for token in doc:
        tokens.append(token)
    return tokens

def get_sections (doc, matcher):
    doc = nlp(doc.text)
    
    print (matcher)
    matches = matcher(doc)
    prev_end = 0
    r_sections = [];
    print ('in sections', matches)
    for id, pos_s, pos_e in matches:
        print ('in matches')
        if(prev_end == 0):
            r_sections.append(doc[prev_end: pos_s])
        else:        
            r_sections.append(doc[prev_end: pos_s])
            print(prev_end, pos_s, pos_e)
        prev_end = pos_s    
    r_sections.append(doc[prev_end: ])
    return r_sections

Doc.set_extension('sections', force = True, method=get_sections)
Doc.set_extension('tokens', method=tokens, force = True)



class IMatcher(object):
    name = 'IMatcher'   

class TermMatcher(IMatcher):
    name = 'TermMatcher'

    def __init__(self, nlp, terms, label):
        patterns = [nlp(text) for text in terms]
        print (patterns)
        self.matcher = PhraseMatcher(nlp.vocab)
        self.matcher.add(label, None, *patterns)

    def __call__(self, doc):
        matches = self.matcher(doc)
        for match_id, start, end in matches:
            span = Span(doc, start, end, label=match_id)
            doc.ents = list(doc.ents) + [span]
        return doc
    
class PatternMatcher(IMatcher):
    name = 'PatternMatcher'

    def __init__(self, nlp, pattern, label):        
        self.matcher = Matcher(nlp.vocab)
        self.matcher.add(label, None, pattern)       

    def __call__(self, doc):
        matches = self.matcher(doc)
        for match_id, start, end in matches:
            span = Span(doc, start, end, label=match_id)
            doc.ents = list(doc.ents) + [span]
        return doc
    
    
nlp = spacy.load('en_core_web_sm')
terms = (u'cat', u'dog', u'tree kangaroo', u'giant sea spider')
phone_pattern = [{'ORTH': '('}, {'SHAPE': 'ddd'}, {'ORTH': ')'}, {'SHAPE': 'ddd'},
           {'ORTH': '-', 'OP': '?'}, {'SHAPE': 'ddd'}]            
            
          


term_entity_matcher = TermMatcher(nlp, terms, 'ANIMAL')
phone_entity_matcher = PatternMatcher(nlp, phone_pattern, 'PHONE_NUMBER')

#phone_entity_matcher1.name = 'test'
#print (phone_entity_matcher.name, phone_entity_matcher1.name)

nlp.add_pipe(term_entity_matcher, after='ner')
nlp.add_pipe(phone_entity_matcher, after='ner')

print(nlp.pipe_names)  # the components in the pipeline
doc = nlp(file_text)
#doc = nlp(u"This is a text about Barack Obama and a dog. Call me at (123) 456 789 or (123) 456 789 or +(123) 456 789")
#rint([(ent.text, ent.label_) for ent in doc.ents])

[cat, dog, tree kangaroo, giant sea spider]
['tagger', 'parser', 'ner', 'PatternMatcher', 'TermMatcher']

NameError: name 'file_text' is not defined

In [ ]:
for token in doc.sents:
    print (token)

In [18]:
#doc._.sections, doc._.tokens()
#doc = nlp(file_text)
matcher = PhraseMatcher(nlp.vocab)
matcher.add('ADDENDUM', None, nlp(u"ADDENDUM"))
sections = doc._.sections(matcher)
len(sections)

<spacy.matcher.PhraseMatcher object at 0x7f6980473b40>
in sections [(7358696156156570218, 6403, 6404), (7358696156156570218, 7445, 7446), (7358696156156570218, 7619, 7620), (7358696156156570218, 11128, 11129), (7358696156156570218, 11400, 11401), (7358696156156570218, 12564, 12565)]
in matches
in matches
6403 7445 7446
in matches
7445 7619 7620
in matches
7619 11128 11129
in matches
11128 11400 11401
in matches
11400 12564 12565

7

In [27]:
doc.vector.shape

(384,)

In [44]:
span0 = doc[:20]
span0 = doc[20:40]
doc.tensor.shape

(14174, 384)

In [35]:
span0.vector.shape

(384,)

In [36]:
span1.vector.shape

(384,)

In [111]:
df_con = Utils.read_data(path = Utils.DATA_PATH + 'construction/')
df_swl = Utils.read_data(path = Utils.DATA_PATH + 'software_license/')

In [136]:
headerRows = 10
def spacy_doc(doc):
    #print ('spacy_doc', doc[0])
    return pd.Series(s_nlp(doc).vector);

df_con_sp= df_con.head(headerRows)['data'].apply(spacy_doc)
df_swl_sp= df_swl.head(headerRows)['data'].apply(spacy_doc)

In [137]:
#df_con_sp_l = list(df_con_sp)
#df_swl_sp_l = list(df_swl_sp)
#df_con_sp
df_con_sp_1 = pd.concat([df_con.head(headerRows), df_con_sp], axis=1)
df_swl_sp_1 = pd.concat([df_swl.head(headerRows), df_swl_sp], axis=1)
df_con_sp

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,-0.039814,0.090090,-0.131850,-0.045305,0.015155,-0.012832,-0.024486,-0.135548,-0.001686,1.925786,...,-0.231340,0.063986,0.016260,-0.041154,-0.043128,-0.066396,-0.066813,-0.090721,0.038902,0.034406
1,-0.029260,0.069030,-0.158370,-0.074306,0.016163,-0.035551,-0.009931,-0.086827,0.004490,1.568128,...,-0.142031,0.053244,-0.010234,-0.051159,-0.019565,-0.069421,-0.027212,-0.099195,0.043741,0.004346
2,-0.016631,0.102082,-0.124143,-0.057256,0.011220,-0.045607,-0.009006,-0.100782,-0.000939,1.736095,...,-0.190262,0.046125,-0.003110,-0.062587,-0.053571,-0.043384,-0.069409,-0.080815,0.030531,0.029149
3,-0.052952,0.096106,-0.169192,-0.060871,0.003365,-0.047491,-0.030239,-0.135937,0.014588,1.902559,...,-0.231327,0.073961,-0.007261,-0.056797,-0.027624,-0.067542,-0.048692,-0.118522,0.046563,0.016372
4,0.007320,0.044456,-0.181889,-0.123598,0.036966,-0.002212,0.026791,-0.053778,-0.006931,1.628716,...,-0.016268,0.028284,-0.014695,-0.063854,-0.043387,-0.121948,-0.034630,-0.101908,0.026873,0.001938
5,-0.029316,0.088818,-0.106279,-0.054309,0.008160,-0.017639,-0.013015,-0.110500,-0.008630,1.708529,...,-0.173281,0.068476,0.002727,-0.052678,-0.054249,-0.037455,-0.056931,-0.069603,0.041576,0.055948
6,-0.038100,0.082554,-0.159500,-0.086310,0.035534,-0.019135,0.007027,-0.083834,0.000272,1.504030,...,-0.086358,0.041396,-0.020733,-0.037539,-0.036805,-0.072145,-0.015519,-0.098173,0.021588,0.014749
7,-0.031790,0.094606,-0.134821,-0.056117,0.016756,-0.059874,-0.026139,-0.135462,0.006222,2.005991,...,-0.257986,0.064240,0.006688,-0.082088,-0.038680,-0.077617,-0.055582,-0.110075,0.051882,0.053333
8,-0.031938,0.066990,-0.149132,-0.064309,0.006025,-0.019926,-0.009881,-0.148332,-0.027492,2.063195,...,-0.245662,0.060704,0.016517,-0.034929,-0.047573,-0.049781,-0.065106,-0.105774,0.059288,0.050280
9,-0.033673,0.092066,-0.123792,-0.045816,0.020717,-0.025082,-0.006770,-0.118473,0.015335,1.733100,...,-0.184954,0.048974,0.008521,-0.033611,-0.032043,-0.074414,-0.075836,-0.090341,0.040204,0.040028

In [110]:
def similarity_matrix(spac_docs):
    len_i = len(spac_docs)
    len_j = len(spac_docs)
    similarity_m = [.0] * len_i
    for i in range(len_i):
        doc_i = spac_docs[i]
        similarity_m[i] = [.0] * len_j
        for j in range(len_j):
            doc_j = spac_docs[j]
            similarity_m[i][j] = doc_i.similarity(doc_j)
    return similarity_m
df_con.head(3)

,data,name,spacy,0,1,2,3,4,5,6,...,290,291,292,293,294,295,296,297,298,299
0,"\n\n\n\n\n\n\nEngineering, Procurement and Con...","1103078_2008-09-05_ENGINEERING, PROCUREMENT AN...","[-0.039813531378222536, 0.09009010402524475, -...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.231340,0.063986,0.016260,-0.041154,-0.043128,-0.066396,-0.066813,-0.090721,0.038902,0.034406
1,\n\n\n\n\n\n\n\n\nSunTrust Bank\n211 Perimeter...,870069_2004-03-30_CONSTRUCTION LOAN AGREEMENT.txt,"[-0.02925968, 0.06903045, -0.15837024, -0.0743...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.142031,0.053244,-0.010234,-0.051159,-0.019565,-0.069421,-0.027212,-0.099195,0.043741,0.004346
2,\n\n\n\n\n\n\n\n\n\n<PAGE> 1\nExhibit 10.42\...,1038914_2001-05-04_CONTRACT FOR CONSTRUCTION &...,"[-0.01663063, 0.102081805, -0.124143414, -0.05...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.190262,0.046125,-0.003110,-0.062587,-0.053571,-0.043384,-0.069409,-0.080815,0.030531,0.029149

In [113]:
#sim_m = similarity_matrix(df_con_sp_l + df_swl_sp_l)
#list(df_con.head(3).spacy.values)
df_con_sp_1

,data,name,0,1,2,3,4,5,6,7,...,290,291,292,293,294,295,296,297,298,299
0,"\n\n\n\n\n\n\nEngineering, Procurement and Con...","1103078_2008-09-05_ENGINEERING, PROCUREMENT AN...",-0.039814,0.090090,-0.131850,-0.045305,0.015155,-0.012832,-0.024486,-0.135548,...,-0.231340,0.063986,0.016260,-0.041154,-0.043128,-0.066396,-0.066813,-0.090721,0.038902,0.034406
1,\n\n\n\n\n\n\n\n\nSunTrust Bank\n211 Perimeter...,870069_2004-03-30_CONSTRUCTION LOAN AGREEMENT.txt,-0.029260,0.069030,-0.158370,-0.074306,0.016163,-0.035551,-0.009931,-0.086827,...,-0.142031,0.053244,-0.010234,-0.051159,-0.019565,-0.069421,-0.027212,-0.099195,0.043741,0.004346
2,\n\n\n\n\n\n\n\n\n\n<PAGE> 1\nExhibit 10.42\...,1038914_2001-05-04_CONTRACT FOR CONSTRUCTION &...,-0.016631,0.102082,-0.124143,-0.057256,0.011220,-0.045607,-0.009006,-0.100782,...,-0.190262,0.046125,-0.003110,-0.062587,-0.053571,-0.043384,-0.069409,-0.080815,0.030531,0.029149

In [138]:
df = pd.concat([df_con_sp, df_swl_sp])
df_1 = pd.concat([df_con_sp_1, df_swl_sp_1])

In [151]:
from sklearn import decomposition
X = df.as_matrix()
pca = decomposition.PCA(.95)
X = pca.fit_transform(X)
#principalDf = pd.DataFrame(data = X, columns = ['principal component 1', 'principal component 2'])
pca.n_components_ , pca.explained_variance_, pca.explained_variance_ratio_  , sum(pca.explained_variance_ratio_), pca.noise_variance_

(10, array([0.09340651, 0.04246008, 0.01964568, 0.01622731, 0.00775485,
        0.00553219, 0.0049078 , 0.00412455, 0.00228816, 0.00194505]), array([0.451228  , 0.20511605, 0.09490432, 0.07839086, 0.0374621 ,
        0.02672491, 0.0237086 , 0.01992485, 0.01105362, 0.00939612]), 0.9579094437187113, 0.0008712961128245747)

In [144]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
print (kmeans.labels_)
kmeans.cluster_centers_

[1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1]

array([[ 4.97279841e-01,  1.07489656e-01,  1.50977870e-04,
        -1.63449719e-02, -3.66064676e-02, -2.64993967e-03,
         1.56755685e-03,  1.50208560e-02,  6.76350601e-03,
        -1.48628165e-02],
       [-1.24319960e-01, -2.68724139e-02, -3.77444674e-05,
         4.08624297e-03,  9.15161689e-03,  6.62484917e-04,
        -3.91889213e-04, -3.75521400e-03, -1.69087650e-03,
         3.71570412e-03]])

In [145]:
df_1['k_cluster'] = kmeans.labels_
#test_feature_df_1 = test_feature_df.join (lineinfo) 
#test_feature_df_1.iloc[:30]

In [147]:
df_1[['name','k_cluster']]

                                                name  k_cluster
0  1103078_2008-09-05_ENGINEERING, PROCUREMENT AN...          1
1  870069_2004-03-30_CONSTRUCTION LOAN AGREEMENT.txt          0
2  1038914_2001-05-04_CONTRACT FOR CONSTRUCTION &...          1
3  843964_2000-03-30_CONSTRUCTION LOAN AGREEMENT ...          1
4  912898_2008-02-22_COLLATERAL ASSIGNMENT OF CON...          0
5  867773_2009-02-26_AMENDMENT TWO TO TURNKEY, EN...          1
6  882259_1998-11-16_CONSTRUCTION LOAN AGREEMENT.txt          0
7  785968_2011-06-16_CONTRACT OF CONSTRUCTION AND...          1
8  1107332_2005-11-08_CONSTRUCTION SERVICES AGREE...          1
9  1016229_1999-11-12_CONTRACT FOR ENGINEERING AN...          1
0  1139650_2004-08-09_AMENDMENT FIVE TO SOFTWARE ...          1
1  783233_1996-02-22_SOFTWARE LICENSE AGREEMENT D...          1
2  1092325_2000-03-23_SOFTWARE LICENSE AND SERVIC...          1
3  751418_2009-05-12_SOFTWARE LICENSE AGREEMENT A...          1
4   896262_2001-11-14_SOFTWARE LICENSE AGREEMENT.txt          1
5  852437_2000-11-21_SERVER SOFTWARE LICENSE AGRE...          1
6  949491_1999-08-16_OBJECT CODE SOFTWARE LICENSE...          1
7  1002422_2013-05-01_REDACTED EXCLUSIVE SOFTWARE...          1
8  1078404_2000-11-14_SOFTWARE LICENSE AGREEMENT ...          0
9  1135906_2009-05-11_SOFTWARE LICENSE AGREEMENT.txt          1